environment                      = "dev"
region                           = "ca-central-1"
state_bucket                     = "terraform-state-270129723225-ca-central-1"
state_bucket_key_path            = "states/tf-infinitt-app-poc/application/terraform.tfstate"
dynamodb_table                   = "terraform-state-lock-270129723225-ca-central-1"
vpc_cidr_block                   = "10.0.0.0/16"
vpc_public_subnets               = ["10.0.0.0/23", "10.0.2.0/23", "10.0.4.0/23"]
vpc_public_subnet_names          = ["Public Subnet One", "Public Subnet Two", "Public Subnet Three"]
vpc_private_subnets              = ["10.0.32.0/19", "10.0.64.0/19", "10.0.96.0/19", "10.0.128.0/19", "10.0.160.0/19", "10.0.192.0/19"]
vpc_private_subnet_names         = ["Private Subnet One", "Private Subnet Two", "Private Subnet Three", "Intra Subnet One", "Intra Subnet Two", "Intra Subnet Three"]
vpc_database_subnets             = ["10.0.224.0/21", "10.0.232.0/21", "10.0.240.0/21"]
vpc_database_subnet_names        = ["DB Subnet One", "DB Subnet Two", "DB Subnet Three"]
create_database_subnet_group     = true
ad_name                          = "example.com"
ad_log_retention_in_days         = 31
kms_key_deletion_window_in_days  = 30
kms_key_enable_rotation          = true
kms_key_name                     = "infinitt-fsx-key"
fsx_file_system_name             = "infinitt-file-system"
fsx_deployment_type              = "SINGLE_AZ_2"
fsx_storage_type                 = "SSD"
ad_manager_instance_type         = "t3a.large"
ad_manager_instance_ec2_key_name = "Infinitt-CA-Central-Test-Key"
tags = {
  ApplicationName = "poc-infinitt"
  GithubRepo      = "infinittna-aws-ollion"
  GithubOrg       = "InfinittNA"
}

