name: Destroy Infinitt Example OIDC Workflow

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [main]
  #   paths: ["terraform/**"]
  # push:
  #   branches: [main]
  #   paths: ["terraform/**"]

jobs:
  networking:
    name: Terraform AWS Infinitt Networking
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: terraform/env/networking
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Current working dir and Repo name
        run: |
          pwd
          echo "repo_name=${{github.repository}}" >> $GITHUB_ENV

      - name: Configure AWS credentials from Test account
        id: get_caller_identity
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role_Terraform
          aws-region: ${{ secrets.AWS_REGION }}
          output-credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # Disable the setup-terraform wrapper and pass outputs using files instead.
          # This is to accommodate very large Terraform plan and apply outputs.
          terraform_wrapper: false
          terraform_version: ${{ secrets.terraform_version }}
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.get_caller_identity.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.get_caller_identity.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.get_caller_identity.outputs.aws-session-token }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=dev.conf
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.get_caller_identity.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.get_caller_identity.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.get_caller_identity.outputs.aws-session-token }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform Destroy
        id: destroy
        # Prevent other users from destroy environment
        if: github.repository_owner == 'OllionDavidCunliffe'
        run: |
          # Write TF Apply output to a file:
          terraform apply -destroy -var-file=env-var-ca-central1-dev.tfvars -auto-approve -no-color 2>&1 | tee /tmp/tfdestroy.txt

          # Remove lines showing TF state refreshes to reduce file size:
          sed -i '/Refreshing state.../d' /tmp/tfdestroy.txt

          # Remove any TF Outputs at the end to reduce file size:
          sed -i '/Outputs/Q' /tmp/tfdestroy.txt